name: image_gallery_downloader
description: Download to gallery images from URL
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.gomezjc.image_gallery_downloader
        pluginClass: ImageGalleryDownloaderPlugin
      ios:
        pluginClass: ImageGalleryDownloaderPlugin
